/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.matchingpairs;

import javax.swing.*;
import java.util.*;
import java.awt.*;

/**
 *
 * @author francescamontagnoli
 */
public class Board extends JFrame implements MatchedListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Board.class.getName());
    
    // number of pairs
    private static final int N = 4;
    
    private final Controller controller;
    
    // list of listeners for the event Shuffle
    private final java.util.List<ShuffleListener> shuffleListeners;
    
    // button that shuffles the values of the cards
    private final JButton shuffleButton;
    // button that exits the game
    private final JButton exitButton;
    
    private final JLabel controllerLabel;
    private final JLabel counterLabel;
    private final JLabel challengeLabel;
    
    private int bestScore = Integer.MAX_VALUE;  // tracks the best score
    
    private final java.util.List<Integer> cardValues;
    private final java.util.List<Card> cards;

    /**
     * Creates new form Board
     */
    public Board() {
        
        // initialize controller
        this.controller = new Controller();
        
        // initialize shuffle listeners list
        this.shuffleListeners = new ArrayList<>();
        
        // initialize buttons
        this.shuffleButton = new JButton("SHUFFLE");
        this.exitButton = new JButton("EXIT");
        
        // initialize labels
        this.controllerLabel = new JLabel("Matched Pairs: 0");
        this.counterLabel = new JLabel("Counter: 0");
        this:challengeLabel = new JLabel("Best Score: /");
        
        this.cardValues = new ArrayList<>(); 
        this.cards = new ArrayList<>();
        
        // initialize the GUI components
        initComponents();
        setupBoard();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setupBoard() {
        // set up the main frame
        setTitle("Matching Pairs Game");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new java.awt.BorderLayout());
        
        // create a panel for the cards with a grid layout
        int[] grid = calculateGrid(N);
        JPanel cardPanel = new JPanel(new java.awt.GridLayout(grid[0], grid[1], 5, 5)); // 2 rows, N columns
        cardPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // create and add cards to the panel
        for (int i = 0; i < 2*N; i++) {
            Card c = new Card(i, 0);
            setupCard(c);
            cardPanel.add(c);
        }
        
        // generate a random sequence of values for the cards
        generateCardValues(N);
        // fire the event shuffle so that each card can take its value from the sequence
        fireShuffleEvent(cardValues);
        
        // create a panel for labels
        JPanel labelPanel = new JPanel(new java.awt.FlowLayout(FlowLayout.CENTER, 25, 10));
        labelPanel.add(controllerLabel);
        labelPanel.add(counterLabel);
        labelPanel.add(challengeLabel);
        
        //create a panel for buttons
        JPanel buttonPanel = new JPanel(new java.awt.FlowLayout(FlowLayout.CENTER));
        buttonPanel.add(shuffleButton);
        buttonPanel.add(exitButton);
        
        // add panels to the frame
        add(cardPanel, java.awt.BorderLayout.CENTER);
        add(labelPanel, java.awt.BorderLayout.NORTH);
        add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        pack();
        setLocationRelativeTo(null); // Center the window
        
        // add action listeners
        shuffleButton.addActionListener(e -> {
            resetGame(cardValues);
        });
        exitButton.addActionListener(e -> System.exit(0));
        // Register board as a matched listener
        controller.addMatchedListener(this);
        
    }
    
    /**
     * @param n 
     * generates 2*n values that go from 1 to n, each repeated twice and then shuffles the values
     */
    private void generateCardValues(int n) {
        for (int i = 0; i < 2*n; i++) {
            int value = (i % n) + 1;
            cardValues.add(value);
        }
        Collections.shuffle(cardValues);
    }
    
    /**
     * @param card 
     * set up one card by setting its state to FACE_DOWN and setting the dimension and the font
     * register the card as an a action listener (card clicked)
     * register the card as a listener for the event shuffle
     * register the card as a listener for the even matched
     * DA FINIRE IL COMMENTO
     */
    private void setupCard(Card card) {
        card.setState(Card.State.FACE_DOWN);
        card.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        card.setPreferredSize(new java.awt.Dimension(80, 80));
        
        card.addActionListener(card);           // register card as a listener for when the card is clicked
        addShuffleListener(card);               // register card as shuffle listener
        controller.addMatchedListener(card);    // register card as matched listener
        card.addPropertyChangeListener(controller);
        card.addVetoableChangeListener(controller);
    }
    
    /**
     * @param cardValues 
     * shuffle the cards after the shuffle button is clicked
     * reset the MatchedPairs label and the Counter label
     */
    private void resetGame(java.util.List<Integer> cardValues) {
        Collections.shuffle(cardValues);
        
        // reset controller state
        controller.resetTurn();
        
        // reset controller and counter labels
        controller.setMatchedPairs(0);
        controller.setCounter(0);
        
        updateMatchedPairsDisplay();
        
        // fire shuffle event to all listeners
        fireShuffleEvent(cardValues);
    }
    
    /**
     * @param matched 
     * 
     */
    @Override
    public void onMatch(Boolean matched) {
        // Update the display whenever a match occurs
        SwingUtilities.invokeLater(() -> {
            updateMatchedPairsDisplay();
        });
        
        // if the game is complete (all cards matched)
        if(matched && controller.getMatchedPairs() == N) {
            int currentScore = controller.getCounter();
            // we got a better score than the current one -> update the challenge label
            if(currentScore < bestScore) {
                bestScore = currentScore;
                challengeLabel.setText("Best Score: " + bestScore);
            }
        }
    }
    
    /**
     * update the text of the MatchedPairs label and the Counter label
     */
    public void updateMatchedPairsDisplay() {
        controllerLabel.setText("Matched Pairs: " + controller.getMatchedPairs());
        counterLabel.setText("Counter: " + controller.getCounter());
    }
    
    /**
     * return true if the game is complete, so if all the pairs have been matched
     * return false otherwise
     */
    public boolean isGameComplete() {
        return controller.getMatchedPairs() == N;
    }
    
    /**
     * @param N
     * @return 
     * calculate how to display the cards in the panel based on the number of total cards
     */
    private int[] calculateGrid(int N) {
        int totalCards = N*2;
        int rows = (int) Math.sqrt(totalCards);
        int cols = (int) totalCards/rows;
        return new int[]{rows, cols};
    }
    
    // add a shuffle listener
    public void addShuffleListener(ShuffleListener listener) {
        shuffleListeners.add(listener);
    }
    
    // remove a shuffle listener
    public void removeShuffleListener(ShuffleListener listener) {
        shuffleListeners.remove(listener);
    }
    
    // fire shuffle event to all registered listeners
    private void fireShuffleEvent(java.util.List<Integer> cardValues) {
        for (ShuffleListener listener : shuffleListeners) {
            listener.onShuffle(cardValues);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Board().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
