/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package com.mycompany.matchingpairs;

import java.awt.Color;
import javax.swing.JButton;
import java.beans.*;
import java.awt.event.*;

/**
 *
 * @author francescamontagnoli
 */
public class Card extends JButton implements ShuffleListener, ActionListener, MatchedListener {
    
    public enum State {
        EXCLUDED, FACE_DOWN, FACE_UP
    }
    
    private int id;
    private int value;
    private State state;    // bound and constrained property
    private VetoableChangeSupport vetos = new VetoableChangeSupport(this);      // helper object for the constrained property (state)
    private PropertyChangeSupport changes = new PropertyChangeSupport(this);    // helper object for the bound property (state)
    

    /**
     * Creates new form Card
     */
    public Card(int id, int value) {
        this.id = id;
        this.value = value;
        this.state = State.FACE_DOWN;
    }
    
    public int getId() {
        return id;
    }
    
    public int getValue() {
        return value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    
    public State getState() {
        return state;
    }
    
    public void setState(State newState) {
        State oldState = this.state;
        try {
            vetos.fireVetoableChange("state", oldState, newState);
            // if no veto then change the card state
            this.state = newState;
            switch (newState) {
                case State.EXCLUDED: 
                    this.setForeground(Color.red);
                    break;
                case State.FACE_DOWN:
                    this.setForeground(Color.green);
                    this.setText("?");
                    break;
                case State.FACE_UP:
                    this.setForeground(Color.black);
                    setText(String.valueOf(this.getValue()));
                    break;
                default:
                    // aggiungere eccezione??
                    break;            
            }
            // fire property change after state is changed
            changes.firePropertyChange("state", oldState, newState);
        } catch (PropertyVetoException e) {
            // code to be executed if
            // change is rejected by somebody
        }
    }
    
    /**
     * 
     * @param evt 
     * action performed when the card is clicked
     * the card state is changed to FACE_UP if no veto is raised
     */
    @Override
    public void actionPerformed(ActionEvent evt) {
        setState(State.FACE_UP);    
    }
    
    /**
     * 
     * @param cardValues 
     * action performed when the shuffle event is fired
     * the card state is changed to FACE_DOWN
     * the card gets a new value
     */
    @Override
    public void onShuffle(java.util.List<Integer> cardValues) {
        // Reset card to face down
        this.setState(State.FACE_DOWN);
        this.setValue(cardValues.get(this.id));
    }
    
    /**
     * 
     * @param matched 
     * action performed when the matched event is fired
     * if the card was matched the state is changed to EXCLUDED
     * otherwise the state is changed to FACE_DOWN after half a second
     */
    @Override
    public void onMatch(Boolean matched) {
        if (this.getState().equals(State.FACE_UP)) {
            if (matched) {
                this.setState(State.EXCLUDED);
            }
            else {
                // timer of half a second so player can see the cards
                javax.swing.Timer timer = new javax.swing.Timer(500, e -> {
                    this.setState(State.FACE_DOWN);
                });
                timer.setRepeats(false);
                timer.start();
            }
        }
    }
    
    @Override
    public void addVetoableChangeListener(VetoableChangeListener l) { 
        vetos.addVetoableChangeListener(l);
    }

    @Override
    public void removeVetoableChangeListener(VetoableChangeListener l) {
        vetos.removeVetoableChangeListener(l);
    }

    @Override
    public void addPropertyChangeListener(PropertyChangeListener l) {
        if (changes == null) {
            this.changes = new PropertyChangeSupport(this);
        }
        changes.addPropertyChangeListener(l);
    }
    
    @Override
    public void removePropertyChangeListener(PropertyChangeListener l) {
        changes.removePropertyChangeListener(l);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
