package matchingpairs;

import javax.swing.*;
import java.util.*;
import java.awt.*;

public class Board extends JFrame implements MatchedListener {

    /**
     * Creates new form Board
     */
    public Board() {
        
        this.N = GlobalState.getNPairs();
        this.multiplayer = GlobalState.isMultiplayer();
        
        // initialize controller
        this.controller = new Controller();
        
        // initialize shuffle listeners list
        this.shuffleListeners = new ArrayList<>();
        
        // initialize game reset event listeners list
        this.gameResetListeners = new ArrayList<>();
        
        // initialize buttons
        this.shuffleButton = new JButton("SHUFFLE");
        this.exitButton = new JButton("EXIT");
        
        // initialize labels
        if(multiplayer) {
            this.controllerLabelP1 = new JLabel("Player 1: 0");
            this.controllerLabelP2 = new JLabel("Player 2: 0");
        }
        else {
            this.controllerLabelP1 = new JLabel("Matched Pairs: 0");
            this.controllerLabelP2 = new JLabel();
        }
        this.turnLabel = new JLabel("Turn: Player 1");
        this.counterLabel = new JLabel("Counter: 0");
        this.challengeLabel = new JLabel("Best Score: /");
        
        // initialize values list
        this.cardValues = new java.util.ArrayList<>();
        // initialize cards map
        this.cards = new HashMap<>(); 
        
        // initialize the GUI components
        initComponents();        
        setupBoard();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sets up the game board by initializing the main frame,
     * creating the cards and GUI components, generating the cardValues,
     * and registering the necessary event listeners
     */
    private void setupBoard() {
        // set up the main frame
        setTitle("Matching Pairs Game");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        // create a panel for the cards with a grid layout
        int[] grid = calculateGrid(N);
        JPanel cardPanel = new JPanel(new GridLayout(grid[0], grid[1], 5, 5));
        cardPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // create and add cards to the panel
        for (int i = 0; i < 2*N; i++) {
            cardValues.add((i % N) + 1);
            Card c = new Card();
            cards.put(c, 0);
            setupCard(c);
            cardPanel.add(c);
        }
        
        // shuffles the sequence of cardValues for the cards
        shuffleCardValues();
        // fire the event shuffle so that each card can take its value from the sequence
        fireShuffleEvent(cards);
        
        // create a panel for labels
        JPanel labelPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 25, 10));
        if (multiplayer) {
            labelPanel.add(controllerLabelP1);
            labelPanel.add(controllerLabelP2);
            turnLabel.setFont(new Font("Arial", Font.BOLD, 16));
            labelPanel.add(turnLabel);
        }
        else {
            labelPanel.add(controllerLabelP1);
        }

        labelPanel.add(counterLabel);
        labelPanel.add(challengeLabel);
        
        // create a panel for buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.add(shuffleButton);
        buttonPanel.add(exitButton);
        
        // add panels to the frame
        add(cardPanel, BorderLayout.CENTER);
        add(labelPanel, BorderLayout.NORTH);
        add(buttonPanel, BorderLayout.SOUTH);
        
        pack();
        setLocationRelativeTo(null); // center the window
        
        // add action listeners
        shuffleButton.addActionListener(e -> {
            resetGame(cards);
        });
        exitButton.addActionListener(e -> {
            int result = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to exit the game?", "Exit Game",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });
        
        // register board as a matched listener
        controller.addMatchedListener(this);
        // register controller as game reset listener
        addGameResetListener(controller);
        
    }
    
    /**
     * Shuffles the values and assign each value to a card
     */
    private void shuffleCardValues() {
        Collections.shuffle(cardValues);
        
        Iterator<Integer> iterator = cardValues.iterator();
        cards.replaceAll((card, value) -> iterator.next());
    }
    
    /**
     * Configures a card by setting its initial state, font, and dimensions
     * Registers the card as an action, shuffle, and match listener, and
     * registers the controller as a property change and vetoable change listener
     *
     * @param card the card to configure
     */
    private void setupCard(Card card) {
        card.setState(Card.State.FACE_DOWN);
        card.setFont(new Font("Arial", Font.BOLD, 24));
        card.setPreferredSize(new Dimension(80, 80));
        
        card.addActionListener(card);
        addShuffleListener(card);
        controller.addMatchedListener(card);
        card.addPropertyChangeListener(controller);
        card.addVetoableChangeListener(controller);
    }
    
    /**
     * Shuffles the cards, resets the MatchedPairs label and the Counter label
     * 
     * @param cardValues list of the cards
     */
    private void resetGame(java.util.Map<Card,Integer> cardValues) {
        shuffleCardValues();
        
        // reset the controller state before starting a new game
        fireGameResetEvent();
        
        updateLabels();
        
        // fire shuffle event to all listeners
        fireShuffleEvent(cardValues);
    }
    
    /**
     * Handles the match event by updating the game display and, when the game is completed, 
     * updating the best score if the current score is better.
     * In multiplayer mode, the score is based on the maximum number of pairs found by either player
     *
     * @param matched true if the two selected cards match, false otherwise
     */
    @Override
    public void onMatch(boolean matched) {
        // Update the display whenever a match occurs
        SwingUtilities.invokeLater(() -> {
            updateLabels();
        });
        
        // if the game is complete (all cards matched)
        if(matched && isGameComplete()) {
            // for singleplayer the best score is smallest number of moves (flipped cards) that was needed to complete the game
            if (!multiplayer) {
                int currentScore = controller.getCounter();
                // we got a better score than the current one -> update the challenge label
                if(currentScore < bestScore) {
                    bestScore = currentScore;
                    challengeLabel.setText("Best Score: " + bestScore);
                }
            }
            // for multiplayer the best score it's the maximum number of pairs matched by some player
            else {
                int currentScore = java.lang.Math.max(controller.getPlayer1Pairs(), controller.getPlayer2Pairs());
                // we got a better score than the current one -> update the challenge label
                if(bestScore == Integer.MAX_VALUE) {
                    bestScore = currentScore;
                    challengeLabel.setText("Best Score: " + bestScore);
                }
                else if(currentScore > bestScore) {
                    bestScore = currentScore;
                    challengeLabel.setText("Best Score: " + bestScore);
                }
            }
        }
    }
    
    /**
     * Updates the labels displaying the current game status
     * In multiplayer mode, it shows the number of pairs found by each player,
     * the current player's turn, and the winner or a tie when the game is complete
     * In single-player mode, it displays the total number of matched pairs
     */
    private void updateLabels() {
        if (multiplayer) {
            controllerLabelP1.setText("Player 1: " + controller.getPlayer1Pairs());
            controllerLabelP2.setText("Player 2: " + controller.getPlayer2Pairs());
            turnLabel.setText("Turn: Player " + controller.getCurrentPlayer());
            if(isGameComplete()) {
                if(controller.getPlayer1Pairs() == controller.getPlayer2Pairs()) {
                    //tie
                    turnLabel.setText("Tie!");
                }
                else if(controller.getPlayer1Pairs() > controller.getPlayer2Pairs()) {
                    //player1 wins
                    turnLabel.setText("Player1 wins!");
                }
                else {
                    //player2 wins
                    turnLabel.setText("Player2 wins!");
                }
            }
        }
        else {
            controllerLabelP1.setText("Matched Pairs: " + controller.getPlayer1Pairs());
        }

        counterLabel.setText("Counter: " + controller.getCounter());
    }
    
    /**
     * Checks whether all pairs have been matched.
     *
     * @return true if all pairs have been matched, false otherwise
     */
    private boolean isGameComplete() {
        return controller.getTotalMatchedPairs() == N;
    }
    
    /**
     * Calculates the number of rows and columns needed to display based on the number of total cards
     * 
     * @param N number of pairs to display
     * @return array containing the number of rows and columns respectively
     */
    private int[] calculateGrid(int N) {
        int totalCards = N*2;
        int rows = (int) Math.sqrt(totalCards);
        int cols = (int) totalCards/rows;
        return new int[]{rows, cols};
    }
    
    // add a shuffle listener
    public void addShuffleListener(ShuffleListener listener) {
        shuffleListeners.add(listener);
    }
    
    // remove a shuffle listener
    public void removeShuffleListener(ShuffleListener listener) {
        shuffleListeners.remove(listener);
    }
    
    // fire shuffle event to all registered listeners
    private void fireShuffleEvent(java.util.Map<Card,Integer> cardValues) {
        for (ShuffleListener listener : shuffleListeners) {
            listener.onShuffle(cardValues);
        }
    }
    
    // add a game reset event listener
    public void addGameResetListener(GameResetListener listener) {
        gameResetListeners.add(listener);
    }

    // remove a game reset event listener
    public void removeGameResetListener(GameResetListener listener) {
        gameResetListeners.remove(listener);
    }
    
    /**
     * Notifies all registered listeners about the termination of the game
     */
    private void fireGameResetEvent() {
        for (GameResetListener listener : gameResetListeners) {
            listener.onGameReset();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    // number of pairs - default is 4
    private int N = 4;
    
    // instance of the controller which handles the game logic
    private final Controller controller;
    
    // list of listeners for the event Shuffle
    private final java.util.List<ShuffleListener> shuffleListeners;
    // list of listeners for the Game Reset event
    private final java.util.List<GameResetListener> gameResetListeners;
    
    // button, when pressed shuffles the cardValues of the cards
    private final JButton shuffleButton;
    // button, when pressed exits the game
    private final JButton exitButton;
    
    // displays the number of pairs matched by player1
    private final JLabel controllerLabelP1;
    // displays the number of pairs matched by player2
    private final JLabel controllerLabelP2;
    // in multiplayer mode, displays the player whose turn is currently active
    private final JLabel turnLabel;
    // displays the total number of times some card is turned face up
    private final JLabel counterLabel;
    // displays the best score seen since the start of the game
    private final JLabel challengeLabel;
    
    /**
     * tracks the best score
     * for singleplayer -> smallest number of moves (flipped cards) that was needed to complete the game
     * for multiplayer -> it's the maximum number of pairs matched by some player
     */
    private int bestScore = Integer.MAX_VALUE;
    
    // list of all the values to assign to each card
    private final java.util.List<Integer> cardValues;
    
    // map of all the cards and their cardValues
    private final java.util.Map<Card, Integer> cards;
    
    // true if the game is in multiplayer mode, false otherwise
    private final boolean multiplayer;
}
